### PR TITLE
Adds 2 files for the desktop integration

### PR DESCRIPTION
**Pull request by trebmuh**
Adds a desktop file (containing a English and French comment) which can be used by anyone, and an icon used by the desktop file for the menu item.
HTH

### CODE REVIEW

**Comment by trebmuh** [comment]
@KaiDrange @fjl ping

**Comment by fjl** [comment]
Hey, I saw your ping, but can't do anything about it. It's KaiDrange's project and he'll need to merge your PR.

**Comment by trebmuh** [comment]
OK, @fjl . Thanks for answering quickly.
Hopefully, @KaiDrange will get this ping.

**Comment by KaiDrange** [comment]
Sorry, I simply forgot. Thanks for the reminder!

**Comment by trebmuh** [comment]
Thanks for the merge.

**Pull request merged**
